-- =============================================================================
--  LAYER 2: DATA WAREHOUSE SETUP
--  File: sql/01_setup_database.sql
--  Run this ONCE before executing the ETL pipeline.
-- =============================================================================

-- Create the database
CREATE DATABASE IF NOT EXISTS rfm_analytics
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE rfm_analytics;

-- =============================================================================
--  TABLE: rfm_scores
--  Populated by the Python ETL pipeline (etl_pipeline.py).
--  This DDL is for reference; SQLAlchemy creates it automatically.
-- =============================================================================
CREATE TABLE IF NOT EXISTS rfm_scores (
    CustomerID      INT             NOT NULL,
    Recency         INT             NOT NULL COMMENT 'Days since last purchase (lower = better)',
    Frequency       INT             NOT NULL COMMENT 'Number of unique invoices',
    Monetary        DECIMAL(12, 2)  NOT NULL COMMENT 'Total revenue (GBP)',
    R_Score         TINYINT         NOT NULL COMMENT 'Recency score 1–5',
    F_Score         TINYINT         NOT NULL COMMENT 'Frequency score 1–5',
    M_Score         TINYINT         NOT NULL COMMENT 'Monetary score 1–5',
    RFM_Score       TINYINT         NOT NULL COMMENT 'Combined score (3–15)',
    RFM_Segment     VARCHAR(3)      NOT NULL COMMENT 'Raw segment string e.g. 554',
    PRIMARY KEY (CustomerID),
    INDEX idx_rfm_score (RFM_Score),
    INDEX idx_recency   (Recency),
    INDEX idx_monetary  (Monetary)
) ENGINE=InnoDB
  COMMENT='RFM scores per customer, generated by ETL pipeline';